{
   "num":"012",
   "name":"butterfree",
   "generation":{
      "num":"generation i",
      "name":"kanto"
   },
   "about":"Butterfree has a superior ability to search for delicious honey from flowers. It can even search out, extract, and carry honey from flowers that are blooming over six miles from its nest.",
   "img":"https://www.serebii.net/pokemongo/pokemon/012.png",
   "size":{
      "height":"1.09 m",
      "weight":"32.0 kg"
   },
   "pokemon-rarity":"normal",
   "type":[
      "bug",
      "flying"
   ],
   "encounter":{
      "base-flee-rate":"0.06",
      "base-capture-rate":"0.125"
   },
   "spawn-chance":"0.022",
   "stats":{
      "base-attack":"167",
      "base-defense":"137",
      "base-stamina":"155",
      "max-cp":"1827",
      "max-hp":"134"
   },
   "resistant":[
      "grass",
      "fighting",
      "ground",
      "bug"
   ],
   "weaknesses":[
      "fire",
      "electric",
      "ice",
      "flying",
      "rock"
   ],
   "quick-move":[
      {
         "name":"confusion",
         "type":"psychic",
         "base-damage":"20",
         "energy":"15",
         "move-duration-seg":"1.6"
      },
      {
         "name":"struggle bug",
         "type":"bug",
         "base-damage":"15",
         "energy":"15",
         "move-duration-seg":"1.5"
      },
      {
         "name":"bug bite",
         "type":"bug",
         "base-damage":"5",
         "energy":"6",
         "move-duration-seg":"0.5"
      }
   ],
   "special-attack":[
      {
         "name":"bug buzz",
         "type":"bug",
         "base-damage":"90",
         "energy":"-50",
         "move-duration-seg":"3.7"
      },
      {
         "name":"psychic",
         "type":"psychic",
         "base-damage":"100",
         "energy":"-100",
         "move-duration-seg":"2.8"
      },
      {
         "name":"signal beam",
         "type":"bug",
         "base-damage":"75",
         "energy":"-50",
         "move-duration-seg":"2.9"
      }
   ],
   "egg":"not in eggs",
   "buddy-distance-km":"1",
   "evolution":{
      "candy":"caterpie candy",
      "prev-evolution":[
         {
            "num":"011",
            "name":"metapod",
            "candy-cost":"50",
            "prev-evolution":[
               {
                  "num":"010",
                  "name":"caterpie",
                  "candy-cost":"12"
               }
            ]
         }
      ]
   }
}